# Generated by Django 4.2.4 on 2023-08-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chathistory_systemcommand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemCommand',
            new_name='ChatGPTSystemCommand',
        ),
    ]
