# Generated by Django 4.2.4 on 2023-09-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_systemcommand_chatgptsystemcommand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGPTSystemCommand',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
