# Generated by Django 4.2.4 on 2023-09-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_message_user_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=10),
        ),
    ]
