# Generated by Django 4.2.4 on 2023-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_message_is_summarized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='role',
            field=models.CharField(choices=[('system', 'system')], default='system', max_length=10),
        ),
    ]
